# Generated by Django 4.1.7 on 2023-02-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_uav_created_time_uav_flighthours_uav_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uav',
            name='additionalNotes',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='uav',
            name='endurance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='uav',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='uav',
            name='maxSpeed',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='uav',
            name='payload',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='uav',
            name='wingspan',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='uav',
            name='flightHours',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='uav',
            name='weight',
            field=models.FloatField(),
        ),
    ]
