# Generated by Django 4.1.7 on 2023-02-21 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_uav_additionalnotes_uav_endurance_uav_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uav',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='uav',
            table='uav',
        ),
    ]
