# Generated by Django 4.1.7 on 2023-02-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_uav_user_alter_uav_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='uav',
            name='isRented',
            field=models.BooleanField(default=True),
        ),
    ]
